#!/bin/bash

XML_DIR=../.fweelin
YML_DIR=yml

usage() {
echo """
xml to yml converter

for use with freewheeling

USAGE
	buildxml [options]

OPTIONS
	-h	display this guide
	-v	display version
	-x	XML to YML
	-y	YML to XML

Conversions happen from XML_DIR to YML_DIR and back.

DEFAULTS:

XML_DIR=~/.fweelin
YML_DIR=yml"""

exit 0
}

version() {
echo 0.1
exit 0
}

xmltoyml() {
for i in $(ls ~/.fweelin/*.xml); do
	FILENAME=$(basename $i .xml)
	echo converting $FILENAME
	./xy -x2y $i > $YML_DIR/$FILENAME.yml
done

exit 0
}

ymltoxml() {
UPDATED=0
for i in $(ls $YML_DIR) ; do
	FILENAME=$(basename $i .yml)

	if [ $YML_DIR/$i -nt $XML_DIR/$FILENAME.xml ] ; then
		echo "updating $i"
		./xy -y2x $YML_DIR/$i > $XML_DIR/$FILENAME.xml && UPDATED=$((UPDATED+1))

	fi
done

if [ $UPDATED -gt 0 ] ; then
echo "Successfully converted $UPDATED records"
fi

exit 0
}

while getopts "hvxy" OPT ; do
	case $OPT in
		h) usage ;;
		v) version ;;
		x) xmltoyml $OPTARG ;;
		y) ymltoxml $OPTARG ;;
		*) usage ;;
	esac
done
